### Login Request
POST http://localhost:35555/login
Content-Type: application/json

{
    "nbm": "10101010",
    "password": "masukinaja"
}

> {% client.token = response.body.token %}

### Protected GET Request
GET http://localhost:35555/inventaris
Authorization: Bearer {{client.token}}
