//home
GET http://localhost:35555/inventaris

//cari
###
GET http://localhost:35555/inventaris/12224

//hapus
###
DELETE http://localhost:35555/inventaris/667db14cc1b2514b46cc094a

//tambah
###
POST http://localhost:35555/inventaris/
Content-Type: application/json

{
    "nama": "mobil",
    "merk": "mainan", 
    "kondisi": "rusak", 
    "tempat": "Lab 2", 
    "tanggalBeli": "123123", 
    "serialnumber": "595955",
    "diperoleh": "RKAS", 
    "status": "ada"
}

//Perbaharui data
###
PATCH http://localhost:35555/inventaris/667db72aaa01aeb365070966
Content-Type: application/json

{
    "nama": "bangku",
    "merk": "kosong", 
    "kondisi": "baik", 
    "tempat": "Lab 1", 
    "tanggalBeli": "123123", 
    "serialnumber": "12224",
    "diperoleh": "mencuri", 
    "status": "hilang"
}