//home
GET http://localhost:35555/inventaris
{ 
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYnVkaSIsIm5ibSI6IjEwMTAxMDEwIiwicm9sZSI6InN1cGVydXNlciIsImlhdCI6MTcxOTYwMDczMSwiZXhwIjoxNzE5Njg3MTMxfQ.bXRJT_YXkBhqmT-IhRtz_vZ5c9mvyArEqcjkuwoE0Yk"
}
//cari
###
GET http://localhost:35555/inventaris/28442

//hapus
###
DELETE http://localhost:35555/inventaris/667efa9b33a7cf23d1d7c6c6

//tambah
###
POST http://localhost:35555/inventaris/
Content-Type: application/json

{
    "nama": "komputer",
    "merk": "apple", 
    "kondisi": "baik", 
    "tempat": "Lab 3", 
    "tanggalBeli": "1848444", 
    "serialnumber": "28442",
    "diperoleh": "RKAS", 
    "status": "ada"
}

//Perbaharui data
###
PATCH http://localhost:35555/inventaris/667db72aaa01aeb365070966
Content-Type: application/json

{
    "nama": "bangku",
    "merk": "kosong", 
    "kondisi": "baik", 
    "tempat": "Lab 1", 
    "tanggalBeli": "123123", 
    "serialnumber": "12224",
    "diperoleh": "mencuri", 
    "status": "hilang"
}

//tambah 2
###
POST http://localhost:35555/inventaris/
Content-Type: application/json

{
    "nama": "meja",
    "merk": "kayu", 
    "kondisi": "rusak", 
    "tempat": "Lab 1", 
    "tanggalBeli": "123123323", 
    "serialnumber": "12311111",
    "diperoleh": "RKAS", 
    "status": "ada"
}

//register user
###
POST http://localhost:35555/register
Content-Type: application/json

{
    "name": "budi",
    "nbm": "10101010", 
    "password": "masukinaja", 
    "role": "superuser"
}

//login user
###
POST http://localhost:35555/login
Content-Type: application/json

{
    "nbm": "10101010", 
    "password": "masukinaja"
}

